import ClointFusion as cf
cf.launch_website_h("https://www.flipkart.com")
cf.mouse_move(700,220)
cf.key_write_enter("8098081320")
print(cf.mouse_click(750,320,single_double_triple='single',copyToClipBoard_Yes_No='yes'))
cf.key_write_enter("ragavan")
print(cf.mouse_click(840,430,single_double_triple='single',copyToClipBoard_Yes_No='yes'))
cf.mouse_click(700,155,single_double_triple='single')
cf.key_write_enter("boAt Airdopes 131 Bluetooth Headset")
cf.mouse_click(cf.mouse_search_snip_return_coordinates_x_y(r"C:\Users\ragav\Downloads\clointfusion_code2\images\Airpod1.png"),single_double_triple='single')
cf.mouse_click(cf.mouse_search_snip_return_coordinates_x_y(r"C:\Users\ragav\Downloads\clointfusion_code2\images\Add_to_cart.png"),single_double_triple='single')
cf.mouse_click(700,155,single_double_triple='single')
cf.key_write_enter("boAt Airdopes 402 Bluetooth Headset")
cf.mouse_click(cf.mouse_search_snip_return_coordinates_x_y(r"C:\Users\ragav\Downloads\clointfusion_code2\images\Airpods2.png"),single_double_triple='single')
cf.mouse_click(cf.mouse_search_snip_return_coordinates_x_y(r"C:\Users\ragav\Downloads\clointfusion_code2\images\Add_to_cart.png"),single_double_triple='single')
cf.mouse_click(cf.mouse_search_snip_return_coordinates_x_y(r"C:\Users\ragav\Downloads\clointfusion_code2\images\order.png"),single_double_triple='single')
cf.key_press('PageDown')
cf.mouse_click(cf.mouse_search_snip_return_coordinates_x_y(r"C:\Users\ragav\Downloads\clointfusion_code2\images\continue.png"),single_double_triple='single')
cf.key_write_enter()S